project:
  type: website
  output-dir: docs

website:
  title: "Lukas Jürgensmeier"
  favicon: images/favicon.png
  site-url: https://lukas-juergensmeier.com
  repo-url: https://github.com/lukas-jue/personal-website
  #repo-actions: [edit, issue]
  google-analytics: "G-SRCXLB0QJK"
  open-graph:
    title: "Lukas Jürgensmeier"
    description: "Lukas Jürgensmeier is a Ph.D. Student and Research Associate in Quantitative Marketing at Goethe University Frankfurt. His research focuses on the interface between Data Science and Marketing. Lukas applies modern econometric methods to novel data sources in the digital economy---especially with the `R` programming language."
  
  navbar:
  #sidebar:
    background: "#eeeeee"#"#0a1952" 
    foreground: "white"
    style: "docked"
    search: true
    left:
    #contents:
      - text: "Home"
        href: index.qmd
      - research.qmd
      - teaching.qmd
      - curriculum-vitae.qmd
      - techacademy.qmd
      - keepar.qmd
      - contact.qmd
  #cookie-consent: true

format:
  html:
    theme:
      light:
        - flatly
        - custom.scss
      # dark:
      #   - darkly
      #   - custom.scss
    css: styles.css
    toc: false
resources:
  - CNAME



