---
title: "Research"
---

My research investigates economic phenomena in the digital economy. I do so using novel big data sources and applying modern statistical methods.

On this website, you will find a summary of my current research projects that use search engine and Amazon product data to assess [fair competition on digital platforms](research.qmd#measuring-fair-competition-on-digital-platforms), as well as smartphone location data and large amounts of unstructured newspaper articles to [estimate the effect of media reporting on consumption](research.qmd#does-media-reporting-matter-for-daily-consumption-choices).

# Working Papers

## Measuring Fair Competition on Digital Platforms

*Authors:* Lukas Jürgensmeier and [Bernd Skiera](https://www.marketing.uni-frankfurt.de/abteilungen/marketing/professoren/skiera/prof-dr-bernd-skiera.html)

*Status:* Revise & Resubmit at the Journal of Marketing

### Abstract

Providers of digital platforms commonly recommend specific platform offers, through labels (e.g., "Amazon's Choice") or through rankings in search results. However, there is currently no systematic way of verifying that a platform's recommendations are fair and neutral, based on offers' merits. This manuscript describes a novel approach to detect discriminatory platform recommendations, by analyzing whether recommendations are dependent on "unfair" factors that do not influence consumers' utility. We focus on a scenario in which a platform provider serves as a platform actor (e.g., Amazon, which sells products on the Amazon Marketplace platform), and might leverage its position to unfairly promote its own offers. We apply our approach to test for discrimination in search visibility on Amazon Marketplace, in two empirical studies covering more than a million daily observations from three countries. Study A, which focuses on identical offers supplied by multiple sellers, does not find consistent evidence that Amazon's search engine results discriminate against third-party sellers. Study B, which compares private-label products supplied exclusively by either Amazon or a third party, finds that Amazon's products are significantly *less* visible than justified. Our approach can serve as a tool for platform actors, regulators, and lawmakers to test for discrimination on platforms.

**Keywords:** Digital Platforms, Amazon, Competition, Antitrust, Search Engines

### Conference Presentations

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Conference                                                                                                                                                                                                                                                                         | Date           | Location                                                                 | Presenting Author                                                                                                         |
+====================================================================================================================================================================================================================================================================================+================+==========================================================================+===========================================================================================================================+
| [17th Symposium on Statistical Challenges in Electronic Commerce Research](https://web.archive.org/web/20210507005842/http://www.scecr.org/) (SCECR 2021)                                                                                                                          | June 2021      | ~~Madrid, Spain~~                                                        | Lukas Jürgensmeier                                                                                                        |
|                                                                                                                                                                                                                                                                                    |                |                                                                          |                                                                                                                           |
|                                                                                                                                                                                                                                                                                    |                | online                                                                   |                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| Interactive Marketing Research Conference (IMRC 2021)                                                                                                                                                                                                                              | October 2021   | ~~Gabelli School of Business, Fordham University, New York City, USA~~   | Lukas Jürgensmeier                                                                                                        |
|                                                                                                                                                                                                                                                                                    |                |                                                                          |                                                                                                                           |
|                                                                                                                                                                                                                                                                                    |                | online                                                                   |                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [13th Paris Conference on Digital Economics 2022](https://sites.google.com/view/parisdigitaleconomics/conference/conference)                                                                                                                                                       | April 2022     | Télécom Paris, Paliseau, France                                          | Lukas Jürgensmeier                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [EMAC Doctoral Colloquium 2022](https://www.uni-corvinus.hu/ind/emac2022)                                                                                                                                                                                                          | May 2022       | Corvinus University, Budapest, Hungary                                   | Lukas Jürgensmeier                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [EMAC Annual Conference 2022](https://www.uni-corvinus.hu/ind/emac2022)                                                                                                                                                                                                            | May 2022       | Corvinus University, Budapest, Hungary                                   | [Bernd Skiera](https://www.marketing.uni-frankfurt.de/abteilungen/marketing/professoren/skiera/prof-dr-bernd-skiera.html) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [Munich Summer Institute 2022](http://munich-summer-institute.org/)                                                                                                                                                                                                                | June 2022      | Bavarian Academy of Sciences and Humanities, Munich, Germany             | Lukas Jürgensmeier                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [ISMS Marketing Science 2022](https://www.chicagobooth.edu/research/kilts/events/isms-marketing-science-conference)                                                                                                                                                                | June 2022      | ~~University of Chicago Booth School of Business, USA~~                  | Lukas Jürgensmeier                                                                                                        |
|                                                                                                                                                                                                                                                                                    |                |                                                                          |                                                                                                                           |
|                                                                                                                                                                                                                                                                                    |                | online                                                                   |                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [20th ZEW Conference on the Economics of Information and Communication Technologies](https://www.zew.de/en/events-and-professional-training/detail/20th-zew-conference-on-the-economics-of-information-and-communication-technologies/3723?cHash=ad35d0cb7616bc26ea8d6603c5c1cd55) | July 2022      | ZEW --- Leibniz Centre for European Economic Research, Mannheim, Germany | Lukas Jürgensmeier                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+
| [SALTY 2022 --- Quantiative Marketing Conference](https://www.whu.edu/en/faculty/marketing-and-sales-group/digital-marketing/salty/)                                                                                                                                               | September 2022 | WHU --- Otto Beisheim School of Management, Düsseldorf, Germany          | Lukas Jürgensmeier                                                                                                        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+--------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+

### Funding

This project is funded by the German Research Foundation (Deutsche Forschungsgemeinschaft--- DFG) through grant number SK 66/8-1 within the project *Visibility in Digital Markets: Risks and Economic Consequences*.

## Does Media Reporting Matter for Daily Consumption Choices?

Authors: Celina Proffen and Lukas Jürgensmeier

### Abstract

Previous research has shown that media reporting matters for voting behavior, investment decisions, and even consumer sentiment as measured in surveys. We provide estimates for how media reporting affects actual consumption choices at a daily level, using data on visits to nearly 200,000 restaurants across the US. Exploiting the variation in news coverage about the recent US-China trade conflict, we estimate that a week-long one standard deviation increase in daily reporting negativity about China leads to 1.3 -- 3.7% fewer daily visits to the average Chinese restaurant in our sample. We furthermore provide evidence that around 65% of this effect is explained by the chosen reporting tone, which holds important implications for policymakers, publishers, and firms' branding strategies. We also link our findings to the literature on consumer ethnocentricity and animosity and provide suggestive evidence that media reporting can trigger ethnocentric behavior.

### Conference Presentations

| Conference                                                                                                       | Date                     | Location                               | Presenting Author  |
|------------------------------------------------------------------------------------------------------------------|--------------------------|----------------------------------------|--------------------|
| [EMAC Doctoral Colloquium 2022](https://www.uni-corvinus.hu/ind/emac2022)                                        | May 2022                 | Corvinus University, Budapest, Hungary | Celina Proffen     |
| [EMAC Annual Conference 2022](https://www.uni-corvinus.hu/ind/emac2022)                                          | May 2022                 | Corvinus University, Budapest, Hungary | Lukas Jürgensmeier |
| [VfS Annual Conference 2022 --- Big Data in Economics](https://www.socialpolitik.de/en/termin/jahrestagung-2022) | September 11 -- 14, 2022 | University of Basel, Switzerland       | Celina Proffen     |

### Funding

This project is funded by the efl -- the Data Science Institute.
