<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lukas Jürgensmeier - keepar</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./images/favicon.png" rel="icon" type="image/png">
<script src="site_libs/cookie-consent/cookie-consent.js"></script>
<link href="site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-SRCXLB0QJK"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-SRCXLB0QJK', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Lukas Jürgensmeier">
<meta property="og:description" content="keepar: An R Package for Online Marketplace Data in Social Science Research">
<meta property="og:site_name" content="Lukas Jürgensmeier">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Lukas Jürgensmeier</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./research.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./curriculum-vitae.html"> 
<span class="menu-text">Curriculum Vitae</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./techacademy.html"> 
<span class="menu-text">TechAcademy</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./keepar.html" aria-current="page"> 
<span class="menu-text">keepar</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./contact.html"> 
<span class="menu-text">Contact</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#aim-facilitating-research-into-online-marketplaces-by-introducing-the-keepar-package-through-an-illustrative-research-project" id="toc-aim-facilitating-research-into-online-marketplaces-by-introducing-the-keepar-package-through-an-illustrative-research-project" class="nav-link" data-scroll-target="#aim-facilitating-research-into-online-marketplaces-by-introducing-the-keepar-package-through-an-illustrative-research-project"><span class="header-section-number">1.1</span> Aim: Facilitating Research into Online Marketplaces by Introducing the <code>keepar</code> Package Through an Illustrative Research Project</a></li>
  <li><a href="#requirement-a-tidy-panel-data-set-of-rubber-ducks" id="toc-requirement-a-tidy-panel-data-set-of-rubber-ducks" class="nav-link" data-scroll-target="#requirement-a-tidy-panel-data-set-of-rubber-ducks"><span class="header-section-number">1.2</span> Requirement: A Tidy Panel Data Set of Rubber Ducks</a></li>
  </ul></li>
  <li><a href="#identifying-acquiring-and-transforming-the-data" id="toc-identifying-acquiring-and-transforming-the-data" class="nav-link" data-scroll-target="#identifying-acquiring-and-transforming-the-data"><span class="header-section-number">2</span> Identifying, Acquiring, and Transforming the Data</a>
  <ul class="collapse">
  <li><a href="#preparation" id="toc-preparation" class="nav-link" data-scroll-target="#preparation"><span class="header-section-number">2.1</span> Preparation</a>
  <ul class="collapse">
  <li><a href="#api-access-and-workspace-setup" id="toc-api-access-and-workspace-setup" class="nav-link" data-scroll-target="#api-access-and-workspace-setup"><span class="header-section-number">2.1.1</span> API Access and Workspace Setup</a></li>
  <li><a href="#load-packages-and-set-up-project-structure" id="toc-load-packages-and-set-up-project-structure" class="nav-link" data-scroll-target="#load-packages-and-set-up-project-structure"><span class="header-section-number">2.1.2</span> Load Packages and Set Up Project Structure</a></li>
  </ul></li>
  <li><a href="#identify-relevant-products" id="toc-identify-relevant-products" class="nav-link" data-scroll-target="#identify-relevant-products"><span class="header-section-number">2.2</span> Identify Relevant Products</a>
  <ul class="collapse">
  <li><a href="#using-the-product-finder-to-obtain-product-asins" id="toc-using-the-product-finder-to-obtain-product-asins" class="nav-link" data-scroll-target="#using-the-product-finder-to-obtain-product-asins"><span class="header-section-number">2.2.1</span> Using the Product Finder to Obtain Product ASINs</a></li>
  <li><a href="#calling-the-product-finder-api-to-obtain-the-asins" id="toc-calling-the-product-finder-api-to-obtain-the-asins" class="nav-link" data-scroll-target="#calling-the-product-finder-api-to-obtain-the-asins"><span class="header-section-number">2.2.2</span> Calling the Product Finder API to Obtain the ASINs</a></li>
  </ul></li>
  <li><a href="#obtaining-raw-product-data" id="toc-obtaining-raw-product-data" class="nav-link" data-scroll-target="#obtaining-raw-product-data"><span class="header-section-number">2.3</span> Obtaining Raw Product Data</a>
  <ul class="collapse">
  <li><a href="#requesting-data-for-up-to-100-products" id="toc-requesting-data-for-up-to-100-products" class="nav-link" data-scroll-target="#requesting-data-for-up-to-100-products"><span class="header-section-number">2.3.1</span> Requesting Data for up to 100 Products</a></li>
  <li><a href="#requesting-data-for-more-than-100-products" id="toc-requesting-data-for-more-than-100-products" class="nav-link" data-scroll-target="#requesting-data-for-more-than-100-products"><span class="header-section-number">2.3.2</span> Requesting Data for More than 100 Products</a></li>
  </ul></li>
  <li><a href="#sec-transform-to-tidy" id="toc-sec-transform-to-tidy" class="nav-link" data-scroll-target="#sec-transform-to-tidy"><span class="header-section-number">2.4</span> Transforming the Raw Data to Tidy Panel Data for our Analysis</a>
  <ul class="collapse">
  <li><a href="#product-metadata" id="toc-product-metadata" class="nav-link" data-scroll-target="#product-metadata"><span class="header-section-number">2.4.1</span> Product Metadata</a></li>
  <li><a href="#historical-event-data" id="toc-historical-event-data" class="nav-link" data-scroll-target="#historical-event-data"><span class="header-section-number">2.4.2</span> Historical Event Data</a></li>
  <li><a href="#other-functions" id="toc-other-functions" class="nav-link" data-scroll-target="#other-functions"><span class="header-section-number">2.4.3</span> Other functions</a></li>
  </ul></li>
  <li><a href="#saving-product-data" id="toc-saving-product-data" class="nav-link" data-scroll-target="#saving-product-data"><span class="header-section-number">2.5</span> Saving Product Data</a></li>
  <li><a href="#sec-transform-to-panel" id="toc-sec-transform-to-panel" class="nav-link" data-scroll-target="#sec-transform-to-panel"><span class="header-section-number">2.6</span> Transforming <em>Event</em> to <em>Panel</em> Data</a>
  <ul class="collapse">
  <li><a href="#interlude-a-note-on-time-zones" id="toc-interlude-a-note-on-time-zones" class="nav-link" data-scroll-target="#interlude-a-note-on-time-zones"><span class="header-section-number">2.6.1</span> Interlude: A Note on Time Zones</a></li>
  <li><a href="#generating-a-daily-panel-of-a-single-variable" id="toc-generating-a-daily-panel-of-a-single-variable" class="nav-link" data-scroll-target="#generating-a-daily-panel-of-a-single-variable"><span class="header-section-number">2.6.2</span> Generating a Daily Panel of a Single Variable</a></li>
  <li><a href="#generating-a-daily-panel-of-multiple-variables" id="toc-generating-a-daily-panel-of-multiple-variables" class="nav-link" data-scroll-target="#generating-a-daily-panel-of-multiple-variables"><span class="header-section-number">2.6.3</span> Generating a Daily Panel of Multiple Variables</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#illustrative-analysis-sales-of-christmas-themed-rubber-ducks" id="toc-illustrative-analysis-sales-of-christmas-themed-rubber-ducks" class="nav-link" data-scroll-target="#illustrative-analysis-sales-of-christmas-themed-rubber-ducks"><span class="header-section-number">3</span> Illustrative Analysis: Sales of Christmas-Themed Rubber Ducks</a>
  <ul class="collapse">
  <li><a href="#identify-christmas-themed-ducks" id="toc-identify-christmas-themed-ducks" class="nav-link" data-scroll-target="#identify-christmas-themed-ducks"><span class="header-section-number">3.1</span> Identify Christmas-Themed Ducks</a></li>
  <li><a href="#visualize-sales-rank-development" id="toc-visualize-sales-rank-development" class="nav-link" data-scroll-target="#visualize-sales-rank-development"><span class="header-section-number">3.2</span> Visualize Sales Rank Development</a></li>
  <li><a href="#difference-in-differences-estimation" id="toc-difference-in-differences-estimation" class="nav-link" data-scroll-target="#difference-in-differences-estimation"><span class="header-section-number">3.3</span> Difference-in-Differences Estimation</a></li>
  </ul></li>
  <li><a href="#summary-conclusions-and-outlook" id="toc-summary-conclusions-and-outlook" class="nav-link" data-scroll-target="#summary-conclusions-and-outlook"><span class="header-section-number">4</span> Summary, Conclusions, and Outlook</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">keepar</h1>
<p class="subtitle lead">keepar: An R Package for Online Marketplace Data in Social Science Research</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="abstract" class="level1 unnumbered">
<h1 class="unnumbered">Abstract</h1>
<p>Researchers frequently use online marketplace data for social science research. However, obtaining and processing such data is cumbersome and often involves web scraping or access to a pre-existing database. One such database is the commercial data provider <a href="https://keepa.com">Keepa</a>, which tracks Amazon products and sellers over time. While this database is accessible via API, identifying, acquiring, and transforming the data into a suitable format for social science research requires significant effort. This article introduces the <code>keepar</code> package, an <code>R</code> package designed to simplify working with this Amazon marketplace data. Through an illustrative research project analyzing the market for rubber ducks on Amazon, this article explains how to use the package to work with <a href="https://keepa.com">Keepa</a> data. By making the corresponding <code>R</code> package open source and available on <a href="https://github.com/lukas-jue/keepar">GitHub</a>, this article aims to facilitate further use of this rich data source in social science research.</p>
</section>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Particularly in business and economics, researchers have frequently used online marketplace data to study digital platforms. One research stream, for example, pertains to how large digital platforms shape competition and how they might engage in self-preferencing—giving preference to their own offers over competing ones <span class="citation" data-cites="reimers2023 farronato2023 waldfogel2024 jürgensmeier2024d jürgensmeier2024b">(e.g., <a href="#ref-reimers2023" role="doc-biblioref">Reimers and Waldfogel 2023</a>; <a href="#ref-farronato2023" role="doc-biblioref">Farronato, Fradkin, and MacKay 2023</a>; <a href="#ref-waldfogel2024" role="doc-biblioref">Waldfogel 2024</a>; <a href="#ref-jürgensmeier2024d" role="doc-biblioref">Jürgensmeier, Bischoff, and Skiera 2024</a>; <a href="#ref-jürgensmeier2024b" role="doc-biblioref">Jürgensmeier and Skiera 2024</a>)</span>.</p>
<p>Unfortunately, obtaining and processing the relevant online marketplace data in sufficient quantity is cumbersome. For example, researchers can use web scraping or query commercial databases of historical marketplace data. While the former comes with legal, ethical, and technical limitations <span class="citation" data-cites="boegershausen2022">(<a href="#ref-boegershausen2022" role="doc-biblioref">Boegershausen et al. 2022</a>)</span>, the latter promises a more convenient avenue for researchers to acquire marketplace data. Such commercial databases typically provide an application programming interface (API) to obtain data. However, users need technical programming expertise to interact with this API and transform the acquired data into a research-suitable format. Even if such technical skills are available, researchers must invest substantial time to understand the API documentation and translate it to code that implements the desired process.</p>
<p>Researchers could better spend this time and effort dealing with research itself—e.g., analyzing the data and drawing conclusions from it. Thus, this article introduces <code>keepar</code>, a package for the programming language <code>R</code>, which simplifies the process of identifying, obtaining, and transforming online marketplace data from <a href="https://keepa.com/">Keepa</a>’s database. With this package, researchers can easily interface with Keepa’s database, which, as of June 2024, contains historical records of more than 4.6 billion products on eleven Amazon marketplaces across the globe <span class="citation" data-cites="keepa2024c">(<a href="#ref-keepa2024c" role="doc-biblioref">Keepa 2024c</a>)</span>.</p>
<p>Keepa has developed software to interface with their API using the programming languages <code>Java</code> <span class="citation" data-cites="keepa2024a">(<a href="#ref-keepa2024a" role="doc-biblioref">Keepa 2024a</a>)</span> and <code>PHP</code> <span class="citation" data-cites="keepa2024b">(<a href="#ref-keepa2024b" role="doc-biblioref">Keepa 2024b</a>)</span>. Additionally, a community-developed Python package exists to access the Keepa database <span class="citation" data-cites="kaszynski2024">(<a href="#ref-kaszynski2024" role="doc-biblioref">Kaszynski 2024</a>)</span>. This article and the corresponding <code>R</code> package make a further contribution to those existing software packages in two main ways.</p>
<p>First, it provides users of <code>R</code> easy access to the Keepa data through the API. Unlike the aforementioned common-purpose programming languages, <code>R</code> was developed specifically for data analysis and visualization <span class="citation" data-cites="ihaka1996">(<a href="#ref-ihaka1996" role="doc-biblioref">Ihaka and Gentleman 1996</a>)</span>. Thus, it is particularly widespread among academics for conducting research <span class="citation" data-cites="giorgi2022">(<a href="#ref-giorgi2022" role="doc-biblioref">Giorgi, Ceraolo, and Mercatelli 2022</a>)</span>. Hence, the <code>keepar</code> package targets users who prefer using <code>R</code> for their entire research project, from obtaining the raw data to estimating statistical models.</p>
<p>Second, the <code>keepar</code> package provides additional functions required to transform the obtained raw data into a format suitable for commonly used statistical methods for social science research. Thus, researchers can leverage the package to identify, acquire, <em>and</em> transform the data into a required format for their research.</p>
<section id="aim-facilitating-research-into-online-marketplaces-by-introducing-the-keepar-package-through-an-illustrative-research-project" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="aim-facilitating-research-into-online-marketplaces-by-introducing-the-keepar-package-through-an-illustrative-research-project"><span class="header-section-number">1.1</span> Aim: Facilitating Research into Online Marketplaces by Introducing the <code>keepar</code> Package Through an Illustrative Research Project</h2>
<p>This article aims to show how social science researchers can use the <code>keepar</code> package to identify, acquire, and transform Amazon marketplace data. To this end, the article seeks to facilitate use of both the package and data by providing and discussing <code>R</code> code for all steps required to implement this analysis—from data acquisition to data transformation to model estimation.</p>
<p>I do so by illustrating a mock research project analyzing the market for rubber ducks. Ultimately, this article shows how researchers can transform the acquired data for use in standard econometric methods. The empirical analysis implements a simple differences-in-differences analysis to estimate how much the sales of Christmas-themed rubber ducks increase during the Christmas season compared to all other rubber ducks.</p>
<p>When consumers <a href="https://www.amazon.com/s?k=rubber+duck">search for “rubber duck” on Amazon</a>, they can choose from many different products. These rubber ducks vary in design, price, and ratings. <a href="#fig-rubber-ducks" class="quarto-xref">Figure&nbsp;1</a> shows some examples of rubber ducks on the first page of the search results—but that is only the beginning. As the subsequent analysis reveals, Amazon lists hundreds of rubber ducks on the marketplace. Using the illustrative example of these little rubber ducks, this article will walk through the functions of the <code>keepar</code> package. While this rubber duck exercise may initially seem a bit silly, it mirrors the relevant steps a social sciences researcher would take when acquiring and analyzing online marketplace data.</p>
<div id="fig-rubber-ducks" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-rubber-ducks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: A Selection of Rubber Ducks on Amazon
</figcaption>
<div aria-describedby="fig-rubber-ducks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/rubber-ducks-amazon.PNG" class="img-fluid figure-img">
</div>
</figure>
</div>
</section>
<section id="requirement-a-tidy-panel-data-set-of-rubber-ducks" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="requirement-a-tidy-panel-data-set-of-rubber-ducks"><span class="header-section-number">1.2</span> Requirement: A Tidy Panel Data Set of Rubber Ducks</h2>
<p>Again, this article aims to facilitate research into online marketplaces by providing an accessible package for most aspects of data identification, acquisition, and preparation for Amazon marketplace data. Before obtaining the raw data, let us define which data structure we require to fulfill this aim. Many standard econometric methods require a tidy panel data set that includes the relevant product information—for example, daily historical price data. What exactly does that mean? We want to create a data set that is</p>
<ul>
<li><p><em>tidy</em> by following the tidy data principle <span class="citation" data-cites="wickham2019">(<a href="#ref-wickham2019" role="doc-biblioref">Wickham et al. 2019</a>)</span>. Most importantly, every column will represent a variable, and every row will represent a single observation of all variables;</p></li>
<li><p>a <em>panel</em>, meaning it includes the historical data of multiple products. Specifically, this means that we have a variable identifying the product (the ASIN—Amazon Standard Identification Number) and one variable identifying the time (often, it will be a date for a daily panel frequency). The combination of <code>ASIN</code> <span class="math inline">\(\times\)</span> <code>date</code> will then uniquely identify each observation, i.e., each row.</p></li>
</ul>
<p>Eventually, the data set should look like <a href="#tbl-mock-data" class="quarto-xref">Table&nbsp;1</a>, which illustrates the above principles.</p>
<div id="tbl-mock-data" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mock-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Tidy Panel Data Set
</figcaption>
<div aria-describedby="tbl-mock-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>ASIN</th>
<th>Date</th>
<th>Price</th>
<th>Sales Rank</th>
<th>…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ASIN-Rubber-Duck-A</td>
<td>today</td>
<td>9.99</td>
<td>2</td>
<td></td>
</tr>
<tr class="even">
<td>ASIN-Rubber-Duck-A</td>
<td>yesterday</td>
<td>8.99</td>
<td>1</td>
<td></td>
</tr>
<tr class="odd">
<td>ASIN-Rubber-Duck-B</td>
<td>today</td>
<td>12.49</td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td>ASIN-Rubber-Duck-B</td>
<td>yesterday</td>
<td>14.99</td>
<td>2</td>
<td></td>
</tr>
<tr class="odd">
<td>…</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>This data structure will allow us to work easily with the data in various ways—be it visualization through <code>ggplot2</code>, data wrangling with <code>dplyr</code>, or regression modeling with <code>fixest</code>. Before estimating sophisticated models, however, we must first identify, acquire, and transform the data.</p>
<p>The remainder of this article walks the reader through these steps. The following section first outlines how to use <code>keepa</code>’s functions to identify, acquire, and transform the data. Then, the article shows how to use this prepared data to conduct an illustrative research project. The last section includes a summary, conclusions, and an outlook for further research.</p>
</section>
</section>
<section id="identifying-acquiring-and-transforming-the-data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Identifying, Acquiring, and Transforming the Data</h1>
<p>Fulfilling our aim—facilitating online marketplace research by making the Keepa data more accessible through the <code>R</code> programming language—requires several steps. In a very simplified outline, we will:</p>
<ol type="1">
<li>Identify the ASINs (i.e., product identifiers) for all relevant products.</li>
<li>Obtain the raw product data for all identified ASINs.</li>
<li>Transform the raw product data into a well-structured panel data set.</li>
</ol>
<p>Before we can do that, however, we must undertake some preparation.</p>
<section id="preparation" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="preparation"><span class="header-section-number">2.1</span> Preparation</h2>
<section id="api-access-and-workspace-setup" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="api-access-and-workspace-setup"><span class="header-section-number">2.1.1</span> API Access and Workspace Setup</h3>
<p>While Keepa offers a free but restricted account, we will require a paid subscription for API access. Currently, the cheapest subscription includes limited access to the API. Depending on how much data you need to download (and how quickly), you might need a more expensive subscription. You can read about the available plans at <a href="https://keepa.com/#!api">Keepa.com/#!api</a>. I recommend starting with the cheapest subscription and upgrading if necessary.</p>
<p>Before we start, please store your private API key. A convenient way is to add this API key as a system environment variable in the <code>.RProfile</code> file. You can use the following code to open the file:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">file.edit</span>(<span class="st">"~/.Rprofile"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, add <code>Sys.setenv("KEEPA_API_KEY" = "insert your private Keepa API Key here")</code> to the <code>.RProfile</code> file. Finally, load the API key into your workspace by running:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>api_key <span class="ot">&lt;-</span> <span class="fu">Sys.getenv</span>(<span class="st">"KEEPA_API_KEY"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us start by loading the <code>keepar</code> package. Before loading it, you must install the package once on your machine by running <code>devtools::install_github("lukas-jue/keepar")</code>. (You also need the package <code>devtools</code>, which you can install through <code>install.packages("devtools")</code>.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(keepar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>While this article introduces the most common functions, you can access the package’s complete documentation, including all available functions, by running the command <code>help(package = keepar)</code>.</p>
<p>You can test whether your API access works by checking your API account’s status:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_status</span>(api_key)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1 x 7</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   timestamp           tokensLeft refillIn refillRate tokenFlowReduction</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;dttm&gt;                   &lt;int&gt; &lt;Period&gt;      &lt;int&gt;              &lt;dbl&gt;</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 2025-01-05 16:32:40        300 40.16S            5                  0</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 2 more variables: tokensConsumed &lt;int&gt;, processingTimeInMs &lt;int&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Every API call costs tokens. The greater the number of products or the more detailed the requested data is, the more tokens it will consume. Calling the API to check its status through <code>check_status</code> does not consume any tokens and returns <code>tokensLeft</code>. This value indicates how many tokens are currently available on your account.</p>
<p>If your token balance becomes negative, you can only make new requests once the balance becomes positive again. Figuring out when this will occur takes some calculations. The following function implements this functionality:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_sufficient_tokens</span>(api_key)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1 x 3</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   tokensBalance secondsUntilTokensPositive datetimeTokensPositive</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;           &lt;int&gt;                      &lt;dbl&gt; &lt;dttm&gt;                </span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1           300                          0 2025-01-05 17:32:40</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-packages-and-set-up-project-structure" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="load-packages-and-set-up-project-structure"><span class="header-section-number">2.1.2</span> Load Packages and Set Up Project Structure</h3>
<p>In addition to the previously loaded <code>keepar</code> package, please load the <code>tidyverse</code> package for visualization and further data processing. Because the data can become voluminous, we will use the fast and highly efficient <code>arrow</code> package to save and read the data in the <code>parquet</code> format. Since we will work with many files and paths, we will also load the <code>fs</code> package to simplify this work.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(arrow)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I suggest setting up an R project, as recommended by <span class="citation" data-cites="bryan2017">Bryan (<a href="#ref-bryan2017" role="doc-biblioref">2017</a>)</span>. Using a project-oriented workflow enables a self-contained project that integrates easily into version control systems and is executable on the local machines of collaborators or others aiming to replicate or extend your analysis. Within this project, please create a folder <code>data</code>, into which we will download and transform the data.</p>
</section>
</section>
<section id="identify-relevant-products" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="identify-relevant-products"><span class="header-section-number">2.2</span> Identify Relevant Products</h2>
<p>First, we want to identify all relevant available rubber ducks on Amazon. But what does <em>all relevant</em> mean? How can we filter for specific products? This section explains and illustrates this selection process. As a first result, we want to count the number of all relevant available rubber ducks in the database.</p>
<section id="using-the-product-finder-to-obtain-product-asins" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="using-the-product-finder-to-obtain-product-asins"><span class="header-section-number">2.2.1</span> Using the Product Finder to Obtain Product ASINs</h3>
<p>Our journey starts on the <a href="https://keepa.com">Keepa</a> website, where we use Keepa’s <a href="https://keepa.com/#!finder">product finder</a> to identify the products whose data we want to download. The product finder lets users filter the database to identify the relevant products. For example, you can filter products from a specific category, within specific price ranges, or offered by particular sellers. After setting the desired filters, we can use this tool to generate a <code>.json</code> file that contains all filters. Later, we can send this <code>.json</code> along with our API request to receive the product identifier—referred to as an ASIN.</p>
<p>After defining the relevant filters, click <code>SHOW API QUERY</code> in the product finder. You will then see a <code>.json</code> file similar to this one:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"title"</span><span class="sc">:</span> <span class="st">"rubber duck"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"trackingSince_lte"</span><span class="sc">:</span> <span class="dv">4733220</span>, </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"categories_include"</span><span class="sc">:</span> [</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"330390011"</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>     <span class="st">"productType"</span><span class="sc">:</span> [</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"0"</span> </span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"hasParentASIN"</span><span class="sc">:</span> false, </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sort"</span><span class="sc">:</span> [</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        [</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            <span class="st">"current_SALES"</span>, </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>            <span class="st">"asc"</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        ]</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"perPage"</span><span class="sc">:</span> <span class="dv">100</span>, </span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"page"</span><span class="sc">:</span> <span class="dv">0</span> </span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Save this <code>.json</code> file in your project directory. I recommend you name it <code>data/1-getASIN/product-finder-api-query.json</code>.</p>
</section>
<section id="calling-the-product-finder-api-to-obtain-the-asins" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="calling-the-product-finder-api-to-obtain-the-asins"><span class="header-section-number">2.2.2</span> Calling the Product Finder API to Obtain the ASINs</h3>
<p>You can obtain the ASINs matching your filter conditions by sending the <code>.json</code> file as a payload to the API. First, you read the <code>.json</code> file into your environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>payload <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_file</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/1-getASIN/product-finder-api-query.json"</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Second, define the marketplace for which you want to get to get ASINs and call the API through <code>get_product_asin()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>domain_id <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>product_asin <span class="ot">&lt;-</span> <span class="fu">get_product_asin</span>(api_key, domain_id, payload)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This call will yield a data frame containing the first 100 ASINs that match your filter criteria (in ascending order by sales rank, i.e., the best-selling product comes first).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>product_asin</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 100 x 1</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin      </span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;     </span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07PB9GVPT</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07SMV3L4V</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B007FPX8Z2</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B01DW6S72Q</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07GMSSXN5</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B008C2F0HQ</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B00DS4EY4S</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07HCQTDK7</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B00ILCA9G4</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 90 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, save this file to the pre-defined folder. Saving the ASINs will make your research more reproducible; since Keepa’s database (and the underlying sales ranks on Amazon) update continuously, re-running the same code later will yield a different set of ASINs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_parquet</span>(product_asin, <span class="st">"data/1-getASIN/asin-page-0.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you only need up to 100 products, you can skip the following paragraphs and jump to the next subsection.</p>
<p>However, you will often want to obtain more than the first 100 ASINs. In this case, we must send multiple requests by iterating through the page variable in the <code>.json</code> file. Here is how you can do that:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>pages <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span> <span class="co"># pages 2 and 3</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> pages) {</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  payload_edited <span class="ot">&lt;-</span> payload <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_replace</span>(<span class="st">"page</span><span class="sc">\\\"</span><span class="st">: 0"</span>, <span class="fu">paste0</span>(<span class="st">"page</span><span class="sc">\\\"</span><span class="st">: "</span>, i))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  product_asin <span class="ot">&lt;-</span> <span class="fu">get_product_asin</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    api_key, domain_id, payload_edited</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_parquet</span>(</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    product_asin, <span class="fu">paste0</span>(<span class="st">"data/1-getASIN/asin-page-"</span>, i, <span class="st">".parquet"</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that, unlike the programming language <code>R</code>, the API request starts counting from <code>0</code>. So the second page is <code>1</code> instead of <code>2</code>. We number the files accordingly, starting from <code>0</code>.</p>
<p>Once you have saved multiple ASIN files, we want to re-read them into our workspace and bind them together to have a list of all ASINs. First, we identify all files on the disk which we want to read in:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>vec_path_asin <span class="ot">&lt;-</span> <span class="fu">dir_ls</span>(<span class="st">"data/1-getASIN/"</span>) <span class="sc">|&gt;</span> <span class="fu">str_subset</span>(<span class="st">"parquet"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>vec_path_asin</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] "data/1-getASIN/asin-page-0.parquet" "data/1-getASIN/asin-page-1.parquet"</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [3] "data/1-getASIN/asin-page-2.parquet"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we read them all at once with the help of <code>purrr::map_dfr</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df_asin <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(vec_path_asin, read_parquet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After reading the data, we can finally answer the initial question: How many rubber ducks are available? We selected quite a narrow set of products with 247 rubber ducks, each represented by its ASIN.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df_asin)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 247</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>However, obtaining the relevant ASINs for our products of interest is only the first step. We now want to analyze the product characteristics.</p>
</section>
</section>
<section id="obtaining-raw-product-data" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="obtaining-raw-product-data"><span class="header-section-number">2.3</span> Obtaining Raw Product Data</h2>
<p>Once we have identified products for which we want to obtain detailed information—by obtaining their ASINs—we can query Keepa’s database to return such information.</p>
<p>First, we create batches of up to 100 ASINs because the Keepa API will only return information on a maximum of 100 products for one API request.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lst_product_batches <span class="ot">&lt;-</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  df_asin <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">batch_id =</span> (<span class="fu">row_number</span>() <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">%/%</span> <span class="dv">100</span>) <span class="sc">|&gt;</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(batch_id) <span class="sc">|&gt;</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">|&gt;</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The newly generated <code>lst_product_batches</code> is a list of data frames that include a maximum of 100 ASINs. Now, we can query the Keepa API for detailed data on each of these ASINs.</p>
<section id="requesting-data-for-up-to-100-products" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="requesting-data-for-up-to-100-products"><span class="header-section-number">2.3.1</span> Requesting Data for up to 100 Products</h3>
<p>First, we build the API request URL for the first 100 ASINs</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>vec_asin <span class="ot">&lt;-</span> lst_product_batches[[<span class="dv">1</span>]]<span class="sc">$</span>asin</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>product_request_url <span class="ot">&lt;-</span> <span class="fu">build_product_url</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  api_key, domain_id, vec_asin,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">offers =</span> <span class="dv">20</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">rating =</span> <span class="dv">1</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">buybox =</span> <span class="dv">1</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we query Keepa’s API by calling the defined URL:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>lst_products <span class="ot">&lt;-</span> <span class="fu">get_product</span>(product_request_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The response is a large list. If it is your first time downloading the data, please take some time to view the raw data through <code>View(lst_products)</code>. The values are not necessarily self-explanatory (which is part of the reason for providing the <code>keepar</code> package). You can read the detailed explanation for each field in Keepa’s <a href="https://keepa.com/#!discuss/t/product-object/116/30">Product Object</a> documentation.</p>
<p>I recommend saving this raw response in <code>.json</code> format to your disk so that you can always return to the raw data later. We use the <code>jsonlite</code> package to save <code>.json</code> files.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>jsonlite<span class="sc">::</span><span class="fu">write_json</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  lst_products,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/2-rawData/0001-raw-data.json"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">auto_unbox =</span> <span class="cn">TRUE</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have now requested and saved data from 100 products. If that is sufficient, you can skip the following subsection and continue with <a href="#sec-transform-to-tidy" class="quarto-xref">Section&nbsp;2.4</a>.</p>
</section>
<section id="requesting-data-for-more-than-100-products" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="requesting-data-for-more-than-100-products"><span class="header-section-number">2.3.2</span> Requesting Data for More than 100 Products</h3>
<p>If you require data on more than 100 products, you must request the data in batches of up to 100 products each. You can execute this request with the following loop, which automates the request timing. Once you have used up all tokens, the loop will automatically wait until your token balance is positive again. Only then will the script execute the subsequent request.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(lst_product_chunks)) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  product_url <span class="ot">&lt;-</span> <span class="fu">build_product_url</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    api_key, domain_id, lst_product_batches[[i]]<span class="sc">$</span>asin,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">offers =</span> <span class="dv">20</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">rating =</span> <span class="dv">1</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">buybox =</span> <span class="dv">1</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># check if there are sufficient tokens, else wait</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  status <span class="ot">&lt;-</span> <span class="fu">check_sufficient_tokens</span>(api_key)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (status<span class="sc">$</span>tokensBalance <span class="sc">&lt;</span> <span class="dv">1</span>) {</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste</span>(</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"waiting"</span>, <span class="fu">round</span>(status<span class="sc">$</span>secondsUntilTokensPositive <span class="sc">/</span> <span class="dv">60</span>, <span class="dv">2</span>),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"minutes until"</span>,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>        <span class="fu">Sys.time</span>() <span class="sc">+</span> status<span class="sc">$</span>secondsUntilTokensPositive <span class="sc">+</span> <span class="dv">60</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"when token balance is positive again"</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">Sys.sleep</span>(status<span class="sc">$</span>secondsUntilTokensPositive <span class="sc">+</span> <span class="dv">60</span>)</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># request data from API</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  lst_products <span class="ot">&lt;-</span> <span class="fu">get_product</span>(product_url)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># save</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>  jsonlite<span class="sc">::</span><span class="fu">write_json</span>(</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>    lst_products,</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>      <span class="st">"data/2-rawData/"</span>,</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>      <span class="fu">formatC</span>(i, <span class="at">width =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"d"</span>, <span class="at">flag =</span> <span class="st">"0"</span>),</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>      <span class="st">"-raw-data.json"</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">auto_unbox =</span> <span class="cn">TRUE</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>  <span class="co"># print status</span></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>      i, <span class="st">"/"</span>, <span class="fu">length</span>(lst_product_chunks), <span class="st">" | "</span>,</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> i <span class="sc">/</span> <span class="fu">length</span>(lst_product_chunks), <span class="dv">0</span>), <span class="st">"% "</span>,</span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>      <span class="st">"of batches saved at "</span>, <span class="fu">Sys.time</span>(),</span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>      <span class="st">" | "</span>, <span class="fu">check_sufficient_tokens</span>(api_key)<span class="sc">$</span>tokensBalance,</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a>      <span class="st">" tokens left"</span>)</span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have now successfully saved all required raw data to our disk. However, we cannot do much with the raw <code>.json</code> files unless we transform them into an appropriate format for typical research methods.</p>
</section>
</section>
<section id="sec-transform-to-tidy" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-transform-to-tidy"><span class="header-section-number">2.4</span> Transforming the Raw Data to Tidy Panel Data for our Analysis</h2>
<p>To transform the raw data, we first read it back into the workspace. Again, we use the <code>purrr</code> package and its <code>map</code> function to read all files into one list.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>vec_path_json <span class="ot">&lt;-</span> <span class="fu">dir_ls</span>(<span class="st">"data/2-rawData/"</span>) <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">str_subset</span>(<span class="st">"json"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>lst_json <span class="ot">&lt;-</span> <span class="fu">map</span>(vec_path_json, jsonlite<span class="sc">::</span>fromJSON)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once we have loaded all the raw data into our workspace, we can extract the relevant data from it.</p>
<p>We do so with a suite of functions, explained in the following subsections. These subsections start with extracting the product metadata and then discuss the extraction of time-varying data, such as prices and sales ranks.</p>
<section id="product-metadata" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="product-metadata"><span class="header-section-number">2.4.1</span> Product Metadata</h3>
<section id="tidy_product-extracts-most-product-level-metadata." class="level4" data-number="2.4.1.1">
<h4 data-number="2.4.1.1" class="anchored" data-anchor-id="tidy_product-extracts-most-product-level-metadata."><span class="header-section-number">2.4.1.1</span> <code>tidy_product</code> extracts most product-level metadata.</h4>
<p>The function <code>tidy_product</code> generates a tidy data frame that includes most of the product metadata in the raw data. Every row corresponds to a single product, identified through its ASIN. This data frame includes, for example, information on the product <code>title</code>, its <code>manufacturer</code>, <code>brand</code>, and <code>rootCategory</code> (i.e., the broadest category of the product).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df_products <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, tidy_product)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>df_products</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 247 x 54</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin       title          domainId lastUpdate          imagesCSV manufacturer</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;      &lt;chr&gt;             &lt;int&gt; &lt;dttm&gt;              &lt;chr&gt;     &lt;chr&gt;       </span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q Rubber Duck B~        1 2024-04-30 13:02:00 71wbjkVH~ LOUHUA      </span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07PB9GVPT Happy Trees D~        1 2024-04-30 13:02:00 511Wd7ip~ Lanterns ho~</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07SMV3L4V 50-Pieces Flo~        1 2024-04-30 13:02:00 51Fm8Kle~ Guaren us   </span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B007FPX8Z2 Rubber Duck N~        1 2024-04-30 13:02:00 41dQMuVN~ Duckshop    </span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B01DW6S72Q Rubber Duck -~        1 2024-04-30 13:02:00 41DO0edx~ Duckshop    </span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07GMSSXN5 Teacher Rubbe~        1 2024-04-30 13:02:00 41fcj9xb~ Ducks in th~</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B008C2F0HQ Waddlers Rubb~        1 2024-04-30 13:02:00 61w5aV1h~ Assurance I~</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B00DS4EY4S Rubber Duck D~        1 2024-04-30 13:02:00 61avUzkp~ Duckshop    </span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07HCQTDK7 Golfer Rubber~        1 2024-04-30 13:02:00 71NYdXNO~ Schnabels   </span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B00ILCA9G4 Dozen Classic~        1 2024-04-30 13:02:00 61e7+eEb~ &lt;NA&gt;        </span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 237 more rows</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 48 more variables: lastPriceChange &lt;dttm&gt;, rootCategory &lt;dbl&gt;,</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   productType &lt;int&gt;, type &lt;chr&gt;, hasReviews &lt;lgl&gt;, trackingSince &lt;dttm&gt;,</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   brand &lt;chr&gt;, productGroup &lt;chr&gt;, partNumber &lt;chr&gt;, model &lt;chr&gt;,</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   color &lt;chr&gt;, size &lt;chr&gt;, packageHeight &lt;int&gt;, packageLength &lt;int&gt;,</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   packageWidth &lt;int&gt;, packageWeight &lt;int&gt;, packageQuantity &lt;int&gt;,</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; #   isAdultProduct &lt;lgl&gt;, isEligibleForTradeIn &lt;lgl&gt;, ...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="get_product_category_tree-extracts-products-category-trees" class="level4" data-number="2.4.1.2">
<h4 data-number="2.4.1.2" class="anchored" data-anchor-id="get_product_category_tree-extracts-products-category-trees"><span class="header-section-number">2.4.1.2</span> <code>get_product_category_tree</code> extracts products’ category trees</h4>
<p>Each product can be listed in multiple categories, organized in a hierarchical category tree. <code>get_product_category_tree</code> extracts this category tree:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df_category_tree <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, get_product_category_tree)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>df_category_tree</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 739 x 4</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin           catId catName             catDepth</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;                  &lt;int&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q 165793011 Toys &amp; Games               1</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07L6BBW2Q 196601011 Baby &amp; Toddler Toys        2</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07L6BBW2Q 330390011 Bath Toys                  3</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B07PB9GVPT 165793011 Toys &amp; Games               1</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B07PB9GVPT 196601011 Baby &amp; Toddler Toys        2</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07PB9GVPT 330390011 Bath Toys                  3</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B07SMV3L4V 165793011 Toys &amp; Games               1</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B07SMV3L4V 196601011 Baby &amp; Toddler Toys        2</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07SMV3L4V 330390011 Bath Toys                  3</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B007FPX8Z2 165793011 Toys &amp; Games               1</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 729 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This data frame contains the category’s ID (<code>catId</code>), name (<code>catName</code>), and depth (<code>catDepth</code>). The latter indicates a category’s position in the category tree: <code>catDepth == 1</code> indicates a product’s broadest category. The higher this value, the narrower (i.e., more specific) the category.</p>
<p>For the first product in the data frame, our category tree appears as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>df_category_tree_first <span class="ot">&lt;-</span> df_category_tree <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(asin <span class="sc">==</span> <span class="st">"B07L6BBW2Q"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>df_category_tree_first</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 3 x 4</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   asin           catId catName             catDepth</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;          &lt;int&gt; &lt;chr&gt;                  &lt;int&gt;</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 B07L6BBW2Q 165793011 Toys &amp; Games               1</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 B07L6BBW2Q 196601011 Baby &amp; Toddler Toys        2</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3 B07L6BBW2Q 330390011 Bath Toys                  3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see that the broadest category is <em>Toys &amp; Games</em>, and the narrowest is <em>Bath Toys</em>. You can quickly access those categories through <code>get_product_broadest_category</code> and <code>get_product_narrowest_category</code>.</p>
</section>
</section>
<section id="historical-event-data" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="historical-event-data"><span class="header-section-number">2.4.2</span> Historical Event Data</h3>
<p>Beyond obtaining the current metadata, we are interested in the historical development of a product’s characteristics. We can obtain such data through the following functions.</p>
<p>Importantly, all historical data is in an <em>event data</em> format. This format means that there will only be a new row in the data frame if the respective information has changed. This format differs from the typical data we use in social sciences, which is often evenly-spaced panel data with a single observation on each day or week. In contrast, <em>event data</em> features an irregularly spaced frequency and can have multiple observations per day or none for weeks, depending on how frequently the underlying product characteristics have changed.</p>
<section id="get_product_price_buybox-extracts-the-products-buy-box-price-history" class="level4" data-number="2.4.2.1">
<h4 data-number="2.4.2.1" class="anchored" data-anchor-id="get_product_price_buybox-extracts-the-products-buy-box-price-history"><span class="header-section-number">2.4.2.1</span> <code>get_product_price_buybox</code> extracts the product’s buy box price history</h4>
<p>Every product on Amazon can have multiple sellers competing to sell the same product. Hence, every product can have various offers. Amazon simplifies the process of consumers picking a seller by recommending a default seller through the buy box. In analyses, it often makes sense to focus on the offer that <em>wins</em> the buy box because most customers buy from this recommended seller <span class="citation" data-cites="zeibak2020 lanxner2019">(<a href="#ref-zeibak2020" role="doc-biblioref">Zeibak 2020</a>; <a href="#ref-lanxner2019" role="doc-biblioref">Lanxner 2019</a>)</span>.</p>
<p>We now extract one of the most relevant historical product characteristics—the price. More precisely, this is the price of the offer occupying the buy box at the given time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df_buybox_price <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, get_product_price_buybox)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df_buybox_price</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 20,465 x 4</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin       datetime            priceBuybox shippingBuybox</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;      &lt;dttm&gt;                    &lt;dbl&gt;          &lt;dbl&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q 2019-03-27 23:34:00        13.0              0</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07L6BBW2Q 2019-04-24 20:30:00        16.0              0</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07L6BBW2Q 2019-04-27 02:04:00        NA               NA</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B07L6BBW2Q 2019-05-06 01:48:00        13.0              0</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B07L6BBW2Q 2019-05-14 08:36:00        12.0              0</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07L6BBW2Q 2019-05-14 21:20:00        12.0              0</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B07L6BBW2Q 2019-05-18 14:42:00        12.0              0</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B07L6BBW2Q 2019-05-19 19:24:00        13.0              0</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07L6BBW2Q 2019-05-27 18:52:00        13.0              0</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B07L6BBW2Q 2019-05-28 19:38:00        13.0              0</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 20,455 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If <code>priceBuybox == NA</code>, then the product did not have an active buy box seller at that particular time. That either means that the product was unavailable or that no seller qualified to <em>win</em> the buy box. Note that the resulting data frame includes two price columns: <code>priceBuybox</code> (the buy box price) and <code>shippingBuybox</code> (the shipping cost of the buy box offer). Often, <code>shippingBuybox</code> is zero. However, I recommend adding both to compute a <code>price</code> variable.</p>
<p>We can now visualize the development of a product’s prices over time. For simplicity, let us focus on the first rubber duck.</p>
<div class="cell fig-cap-location-top">
<div class="sourceCode cell-code" id="cb26" data-cap-location="top"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>vec_asin_filter <span class="ot">&lt;-</span> df_buybox_price <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(asin) <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>()</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>vec_title <span class="ot">&lt;-</span> df_products <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(asin <span class="sc">%in%</span> vec_asin_filter) <span class="sc">|&gt;</span> <span class="fu">select</span>(title) <span class="sc">|&gt;</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>() <span class="sc">|&gt;</span> <span class="fu">str_sub</span>(<span class="dv">1</span>, <span class="dv">43</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>df_buybox_price <span class="sc">|&gt;</span> </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(asin <span class="sc">%in%</span> vec_asin_filter) <span class="sc">|&gt;</span> </span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price =</span> priceBuybox <span class="sc">+</span> shippingBuybox) <span class="sc">|&gt;</span> </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(datetime, price)) <span class="sc">+</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_step</span>() <span class="sc">+</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>dollar) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Product: "</span>, vec_title),</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Price"</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-buy-box-price" class="quarto-figure quarto-figure-center quarto-float anchored" data-cap-location="top">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-buy-box-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Buy Box Price Development of the First Rubber Duck in the Data Set
</figcaption>
<div aria-describedby="fig-buy-box-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="keepar_files/figure-html/fig-buy-box-price-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p><a href="#fig-buy-box-price" class="quarto-xref">Figure&nbsp;2</a> already provides rich information on the product. We can see that the prices of rubber ducks vary strongly over time. While the cheapest available price over time is $7.99, the offer peaked at double this price ($15.99) for short durations.</p>
<p>Because the line indicating the price is missing for some dates, we can conclude that the product was not always available—if the price is missing, it implies that no seller <em>won</em> the buy box.</p>
</section>
<section id="get_product_buybox_history-extracts-the-products-buy-box-seller-history" class="level4" data-number="2.4.2.2">
<h4 data-number="2.4.2.2" class="anchored" data-anchor-id="get_product_buybox_history-extracts-the-products-buy-box-seller-history"><span class="header-section-number">2.4.2.2</span> <code>get_product_buybox_history</code> extracts the product’s buy box seller history</h4>
<p>You can obtain information on which seller <em>won</em> the buy box at which time through <code>get_product_buybox_history</code>. Note that this function only works if you specify <code>build_product_url(..., buybox = 1)</code> such that the raw data includes information on the buy box history.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df_buybox_history <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, get_product_buybox_history)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>df_buybox_history</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 11,932 x 3</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin       datetime            buyBoxSeller        </span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;      &lt;dttm&gt;              &lt;chr&gt;               </span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q 2019-03-27 23:34:00 AC5QQUYS4DT2W       </span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07L6BBW2Q 2019-04-27 02:04:00 noSellerQualifiedBB </span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07L6BBW2Q 2019-05-06 01:48:00 AC5QQUYS4DT2W       </span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B07L6BBW2Q 2019-05-14 21:20:00 A2PNVNIOI1WGC       </span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B07L6BBW2Q 2019-05-18 14:42:00 AC5QQUYS4DT2W       </span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07L6BBW2Q 2019-05-27 18:52:00 A12SR7AJCMRNG9      </span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B07L6BBW2Q 2019-05-30 04:54:00 noSellerOrOutOfStock</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B07L6BBW2Q 2019-06-05 09:24:00 AC5QQUYS4DT2W       </span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07L6BBW2Q 2019-06-27 15:58:00 A3G1S0O0LEO4WI      </span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B07L6BBW2Q 2019-07-07 11:52:00 AC5QQUYS4DT2W       </span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 11,922 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you are interested in other prices, you can call <code>get_product_price_amazon</code> (for the price offered by Amazon as the seller) and <code>get_product_price_marketplace</code> (for the lowest non-Amazon offer).</p>
</section>
<section id="get_product_sales_rank_reference-extracts-the-sales-rank-history-for-the-reference-category" class="level4" data-number="2.4.2.3">
<h4 data-number="2.4.2.3" class="anchored" data-anchor-id="get_product_sales_rank_reference-extracts-the-sales-rank-history-for-the-reference-category"><span class="header-section-number">2.4.2.3</span> <code>get_product_sales_rank_reference</code> extracts the sales rank history for the reference category</h4>
<p>We can obtain the sales rank history to analyze how well a product has sold. The sales rank is a proxy for sales based on the following simplified logic: Amazon ranks all products by sales for a specific product category. The best-selling product in the category receives the sales rank <code>1</code>, the second-best-selling product receives sales rank <code>2</code>, and so on. Hence, the absolute value of the sales rank is only comparable <em>within</em> the same category.</p>
<p>Amazon provides—and Keepa tracks—different sales ranks for the same product. Often, the sales rank for a product’s <em>reference category</em> (also called <em>root category</em>) is useful—the reference category is the broadest available category. Hence, chances are highest that similar products fall into the same reference category, making the products’ sales ranks directly comparable.</p>
<p>You can extract the products’ sales ranks for the reference category through <code>get_product_sales_rank_reference</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df_salesRank <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, get_product_sales_rank_reference)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df_salesRank</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 366,810 x 4</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin       datetime            salesRankReference salesRank</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;      &lt;dttm&gt;              &lt;chr&gt;                  &lt;int&gt;</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q 2018-12-27 19:00:00 165793011            4140161</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07L6BBW2Q 2018-12-29 22:50:00 165793011             264291</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07L6BBW2Q 2019-01-01 19:52:00 165793011             173252</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B07L6BBW2Q 2019-01-10 09:50:00 165793011              56206</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B07L6BBW2Q 2019-01-11 03:02:00 165793011              32908</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07L6BBW2Q 2019-01-12 15:36:00 165793011              58844</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B07L6BBW2Q 2019-01-13 18:56:00 165793011              94892</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B07L6BBW2Q 2019-01-14 01:10:00 165793011             126124</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07L6BBW2Q 2019-01-15 13:12:00 165793011              48033</span></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B07L6BBW2Q 2019-01-17 04:24:00 165793011             130129</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 366,800 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see from the number of observations in the resulting data frame, the sales rank data is comparatively abundant: 247 products yield 366,810 sales rank observations. Hence, it might be advisable to restrict your observation period to the smallest required time frame.</p>
</section>
<section id="get_product_rating-extracts-the-products-star-rating-history" class="level4" data-number="2.4.2.4">
<h4 data-number="2.4.2.4" class="anchored" data-anchor-id="get_product_rating-extracts-the-products-star-rating-history"><span class="header-section-number">2.4.2.4</span> <code>get_product_rating</code> extracts the products’ star rating history</h4>
<p>How well did consumers like the product over time? You can answer this question by extracting the products’ rating history, which shows a product’s star rating at historical points in time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_rating <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, get_product_rating)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>df_rating</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 1,937 x 3</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin       datetime            rating</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;      &lt;dttm&gt;               &lt;dbl&gt;</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q 2019-03-27 23:34:00    5  </span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07L6BBW2Q 2019-04-16 03:12:00    4.5</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07L6BBW2Q 2019-04-18 01:26:00    4.6</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B07L6BBW2Q 2019-05-06 01:48:00    4.7</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B07L6BBW2Q 2019-05-14 02:40:00    4.3</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07L6BBW2Q 2019-05-19 19:24:00    4.2</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B07L6BBW2Q 2019-05-23 14:08:00    4.3</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B07L6BBW2Q 2019-05-28 19:38:00    4.4</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07L6BBW2Q 2019-06-10 22:24:00    4.5</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B07L6BBW2Q 2019-06-23 06:12:00    4.1</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 1,927 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="get_product_reviews-extracts-the-products-history-of-number-of-reviews" class="level4" data-number="2.4.2.5">
<h4 data-number="2.4.2.5" class="anchored" data-anchor-id="get_product_reviews-extracts-the-products-history-of-number-of-reviews"><span class="header-section-number">2.4.2.5</span> <code>get_product_reviews</code> extracts the products’ history of number of reviews</h4>
<p>Beyond the star rating, you can also extract the number of reviews the given product had at past dates in its history. You can extract this historical information through <code>get_product_reviews</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df_count_reviews <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(lst_json, get_product_reviews)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df_count_reviews</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 9,640 x 3</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    asin       datetime            countReviews</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;chr&gt;      &lt;dttm&gt;                     &lt;int&gt;</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 B07L6BBW2Q 2019-03-27 23:34:00            1</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 B07L6BBW2Q 2019-04-16 03:12:00            2</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 B07L6BBW2Q 2019-04-18 01:26:00            3</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 B07L6BBW2Q 2019-05-06 01:48:00            4</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 B07L6BBW2Q 2019-05-14 02:40:00            5</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 B07L6BBW2Q 2019-05-19 19:24:00            6</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 B07L6BBW2Q 2019-05-20 11:56:00            7</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 B07L6BBW2Q 2019-05-23 14:08:00            8</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 B07L6BBW2Q 2019-05-28 19:38:00            9</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 B07L6BBW2Q 2019-05-30 04:54:00           10</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 9,630 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="other-functions" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="other-functions"><span class="header-section-number">2.4.3</span> Other functions</h3>
<p>The <code>keepar</code> package contains some more functions to extract data from product objects. These include <code>get_product_offers</code> to check a product’s offers (i.e., which sellers have offered the product at least once) and <code>get_product_offers_history</code> to obtain the historical prices of those sellers’ offers.</p>
</section>
</section>
<section id="saving-product-data" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="saving-product-data"><span class="header-section-number">2.5</span> Saving Product Data</h2>
<p>Once you have extracted all relevant product data, you can save those to your disk. I recommend doing so since the data might become larger than your available memory once you combine the individual data in the next section. We can follow our initial folder structure and create a new <code>data/3-tidyData/</code> folder for the <em>tidy</em>-ed data.</p>
<p>We can either save the data individually by data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_parquet</span>(df_products, <span class="st">"data/3-tidyData/df_products.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or we can save them all at once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a list with all data frames to save</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lst</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  df_products, df_category_tree, df_buybox_price,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  df_buybox_history, df_salesRank, df_rating,</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  df_count_reviews</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># save all data frames from the list individually</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">iwalk</span>(</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    \(x, y) <span class="fu">write_parquet</span>(</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>      x, <span class="fu">paste0</span>(<span class="st">"data/3-tidyData/"</span>, y, <span class="st">".parquet"</span>)</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-transform-to-panel" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="sec-transform-to-panel"><span class="header-section-number">2.6</span> Transforming <em>Event</em> to <em>Panel</em> Data</h2>
<p>Until now, we have extracted product <em>meta</em> or <em>event</em> data from the raw product data. This manner of storing the raw data is efficient—you only have to record a new row when a product attribute (e.g., its price) has changed. However, many typical methods—for example (fixed effects) regressions—require evenly-spaced (panel) data.</p>
<p>Thus, we must convert the unevenly-spaced <em>event</em> data set to an evenly-spaced panel data set. Also, we only have individual variables stored in individual data frames (e.g., prices and sales ranks are in two different data sets). Thus, we want to create a single panel data set that features a single observation per day per product, and which includes all previously introduced historical product variables (e.g., prices, sales ranks, and ratings).</p>
<p>First, we read all previously saved data frames from the <code>data/3-tidyData</code> folder into a list called <code>lst_df</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>vec_path <span class="ot">&lt;-</span> <span class="st">"data/3-tidyData"</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>lst_df <span class="ot">&lt;-</span> <span class="fu">dir_ls</span>(vec_path) <span class="sc">|&gt;</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(read_parquet) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_names</span>(</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">basename</span>(<span class="fu">dir_ls</span>(vec_path)) <span class="sc">|&gt;</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_remove_all</span>(<span class="st">".parquet"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="interlude-a-note-on-time-zones" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="interlude-a-note-on-time-zones"><span class="header-section-number">2.6.1</span> Interlude: A Note on Time Zones</h3>
<p>Before we can start transforming the data—specifically, transforming the <code>datetime</code> variable from irregularly-spaced <em>events</em> to regularly-spaced <em>daily</em> frequency—we must consider time zones. All <code>datetime</code> values in the above data frames are in <em>Coordinated Universal Time</em> (UTC). For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df_rating <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(datetime)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] "2019-03-27 23:34:00 UTC"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you want to merge the above data with external data sources in local time, you need to transform the <code>datetime</code> variable. For example, the offset between UTC and Eastern Standard Time (EST) on the United States Amazon marketplace is -5 hours. We can transform the time zones with <code>lubridate</code>’s <code>with_tz()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>df_rating <span class="sc">|&gt;</span> <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span> <span class="fu">pull</span>(datetime) <span class="sc">|&gt;</span> <span class="fu">with_tz</span>(<span class="st">"EST"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] "2019-03-27 18:34:00 EST"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we want to transform all <code>datetime</code> in the <code>lst_df</code> data frames into the EST time zone, we can run the following code across all elements of <code>lst_df</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lst_df <span class="ot">&lt;-</span> lst_df <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    \(x) x <span class="sc">|&gt;</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">across</span>(</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">where</span>(is.POSIXct),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>          \(y) <span class="fu">with_tz</span>(y, <span class="st">"EST"</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generating-a-daily-panel-of-a-single-variable" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="generating-a-daily-panel-of-a-single-variable"><span class="header-section-number">2.6.2</span> Generating a Daily Panel of a Single Variable</h3>
<p>Let us now start transforming the data from <em>event</em> to daily <em>panel</em> data. This subsection uses the buy box price data in <code>df_buybox_price</code> to explain the process and then provides the code for other variables.</p>
<section id="buy-box-price" class="level4" data-number="2.6.2.1">
<h4 data-number="2.6.2.1" class="anchored" data-anchor-id="buy-box-price"><span class="header-section-number">2.6.2.1</span> Buy Box Price</h4>
<p>First, however, we need to decide on which observation to use as <em>the</em> daily observation if there is more than one observation per day. Some options would be taking the mean, median, or the first or last price of the day. In the following, we take a cue from <span class="citation" data-cites="jürgensmeier2024b">Jürgensmeier and Skiera (<a href="#ref-jürgensmeier2024b" role="doc-biblioref">2024</a>)</span> and use the last daily observation to represent the daily value.</p>
<p>We start by extracting the last observation on each day for each product.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df_price_daily_raw <span class="ot">&lt;-</span> lst_df<span class="sc">$</span>df_buybox_price <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price =</span> priceBuybox <span class="sc">+</span> shippingBuybox) <span class="sc">|&gt;</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(datetime),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">isPriceNa =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(price), <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(asin, date) <span class="sc">|&gt;</span> </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="fu">n</span>()) <span class="sc">|&gt;</span> <span class="co"># last observation: n(); first observation: 1</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">isPriceChange =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We then create a <em>grid</em> data frame—containing one row for each product and each date—and <em>left join</em> it with <code>df_price_daily_raw</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>df_grid <span class="ot">&lt;-</span> df_price_daily_raw <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">construct_ts_grid_by_group</span>()</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>df_price_daily <span class="ot">&lt;-</span> df_grid <span class="sc">|&gt;</span> </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_price_daily_raw, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"asin"</span>, <span class="st">"date"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fill</span>(<span class="fu">c</span>(price , isPriceNa), <span class="at">.direction =</span> <span class="st">"down"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(<span class="fu">list</span>(<span class="at">isPriceChange =</span> <span class="cn">FALSE</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price =</span> <span class="fu">if_else</span>(isPriceNa <span class="sc">==</span> <span class="cn">TRUE</span>, <span class="fu">as.numeric</span>(<span class="cn">NA</span>), price)) <span class="sc">|&gt;</span> </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(datetime, priceBuybox, shippingBuybox))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This procedure yields a tidy panel data set with daily frequency including all buy box prices.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df_price_daily</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 288,037 x 5</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    date       asin       price isPriceNa isPriceChange</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;date&gt;     &lt;chr&gt;      &lt;dbl&gt; &lt;lgl&gt;     &lt;lgl&gt;        </span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1 2017-05-26 B00001U0RG  9.99 FALSE     TRUE         </span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2 2017-05-27 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3 2017-05-28 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4 2017-05-29 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5 2017-05-30 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6 2017-05-31 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7 2017-06-01 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8 2017-06-02 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9 2017-06-03 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10 2017-06-04 B00001U0RG  9.99 FALSE     FALSE        </span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # i 288,027 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that this data frame has one observation for each date and product—irrespective of whether <code>df_price_daily_raw</code> contained an observation for that day. In the above code, <code>fill(..., .direction = "down")</code> fills all <code>NA</code> values in a downward direction with the last non-<code>NA</code> value. This procedure is valid because Keepa only stores an entry in the <em>event</em> data sets if the underlying value (e.g., the price) changes. Thus, if there is no entry in the raw data, the price remains unchanged, and we can replace the <code>NA</code> value with the last known price. Similarly, if the buy box was unavailable, i.e., the price in <code>df_price_daily_raw</code> is <code>NA</code>, the above code ensures that the below values will remain <code>NA</code> until the buy box becomes available again.</p>
</section>
<section id="sales-rank" class="level4" data-number="2.6.2.2">
<h4 data-number="2.6.2.2" class="anchored" data-anchor-id="sales-rank"><span class="header-section-number">2.6.2.2</span> Sales Rank</h4>
<p>Similar to the buy box price, we can transform the sales rank <em>event</em> to <em>panel</em> data through the following process:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>df_sales_rank_daily_raw <span class="ot">&lt;-</span> lst_df<span class="sc">$</span>df_salesRank <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">date =</span> <span class="fu">as.Date</span>(datetime),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">isSalesRankNa =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(salesRank), <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(asin, date) <span class="sc">|&gt;</span> </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="fu">n</span>())</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>df_salesrank_daily <span class="ot">&lt;-</span> df_sales_rank_daily_raw <span class="sc">|&gt;</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">construct_ts_grid_by_group</span>() <span class="sc">|&gt;</span> </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_sales_rank_daily_raw, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"asin"</span>, <span class="st">"date"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fill</span>(</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(salesRank, salesRankReference, isSalesRankNa),</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">.direction =</span> <span class="st">"down"</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">salesRank =</span> <span class="fu">if_else</span>(</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>    isSalesRankNa <span class="sc">==</span> <span class="cn">TRUE</span>, <span class="fu">as.integer</span>(<span class="cn">NA</span>), salesRank)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>datetime)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="generating-a-daily-panel-of-multiple-variables" class="level3" data-number="2.6.3">
<h3 data-number="2.6.3" class="anchored" data-anchor-id="generating-a-daily-panel-of-multiple-variables"><span class="header-section-number">2.6.3</span> Generating a Daily Panel of Multiple Variables</h3>
<p>We have now generated two panel data sets, one for the <code>price</code> variable and one for the <code>salesRank</code> variable. The following commands join those individual panels and generate a full panel data set that includes both variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>df_panel_joined <span class="ot">&lt;-</span> df_salesrank_daily <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(df_price_daily, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"asin"</span>, <span class="st">"date"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can use the <code>skim()</code> function from the <code>skimr</code> package to easily generate the summary statistics for the resulting panel data set. This data set contains the daily information regarding prices and sales ranks for each product and enables us to use standard statistical methods, such as fixed-effects regression analyses, which often require evenly-spaced panel data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(df_panel_joined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">df_panel_joined</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">458584</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">logical</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 12%">
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">asin</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">247</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">salesRankReference</td>
<td style="text-align: right;">36144</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">date</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">2015-02-01</td>
<td style="text-align: left;">2024-04-30</td>
<td style="text-align: left;">2020-11-11</td>
<td style="text-align: right;">3377</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 7%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">isSalesRankNa</td>
<td style="text-align: right;">12827</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: left;">FAL: 398498, TRU: 47259</td>
</tr>
<tr class="even">
<td style="text-align: left;">isPriceNa</td>
<td style="text-align: right;">170547</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;">FAL: 250725, TRU: 37312</td>
</tr>
<tr class="odd">
<td style="text-align: left;">isPriceChange</td>
<td style="text-align: right;">170547</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: left;">FAL: 272977, TRU: 15060</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">salesRank</td>
<td style="text-align: right;">60086</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">956370.58</td>
<td style="text-align: right;">1369065.71</td>
<td style="text-align: right;">446.00</td>
<td style="text-align: right;">299205.0</td>
<td style="text-align: right;">622698.00</td>
<td style="text-align: right;">1131003.00</td>
<td style="text-align: right;">13925552.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">price</td>
<td style="text-align: right;">207859</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">15.31</td>
<td style="text-align: right;">8.86</td>
<td style="text-align: right;">2.44</td>
<td style="text-align: right;">10.3</td>
<td style="text-align: right;">13.89</td>
<td style="text-align: right;">16.99</td>
<td style="text-align: right;">124.1</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These summary statistics conclude the section on identifying, obtaining, and transforming product data with the <code>keepar</code> package and lead us toward the data analysis.</p>
</section>
</section>
</section>
<section id="illustrative-analysis-sales-of-christmas-themed-rubber-ducks" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Illustrative Analysis: Sales of Christmas-Themed Rubber Ducks</h1>
<p>Once we have generated a suitable data set, we can use it for our analyses. This section shows how to use the generated panel data for an illustrative difference-in-differences analysis, as pioneered by <span class="citation" data-cites="card1993">Card and Krueger (<a href="#ref-card1993" role="doc-biblioref">1993</a>)</span> and discussed in detail in canonical textbooks <span class="citation" data-cites="angrist2009a">(e.g., <a href="#ref-angrist2009a" role="doc-biblioref">Angrist and Pischke 2009</a>)</span>.</p>
<p>Imagine you are a rubber duck seller offering a variety of differently-themed rubber ducks. You suspect that consumers would likely purchase more rubber ducks during the period leading up to Christmas. Furthermore, you suspect that these additional Christmas sales would be even higher for Christmas-themed rubber ducks relative to other types. To increase your sales, you decided to introduce Christmas-themed rubber ducks one year ago.</p>
<p>After this year, you want to evaluate how well your Christmas-themed rubber ducks sold <em>in comparison</em> to all other rubber ducks <em>during</em> the Christmas season. An appropriate method for such an assessment is a difference-in-differences analysis. With this approach, you can estimate how the Christmas season affects sales of Christmas-themed rubber ducks compared to other kinds of rubber ducks, as measured by a product’s sales rank.</p>
<section id="identify-christmas-themed-ducks" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="identify-christmas-themed-ducks"><span class="header-section-number">3.1</span> Identify Christmas-Themed Ducks</h2>
<p>Before we can start this analysis, we have to identify all Christmas-themed rubber ducks. We do so by checking whether the <code>title</code> variable in the data frame <code>df_products</code> contains either the word <code>Santa</code> or <code>Christmas</code> (without case sensitivity).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>df_products_isChristmasDuck <span class="ot">&lt;-</span> df_products <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasDuck =</span> <span class="fu">if_else</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">str_detect</span>(</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>        title, <span class="st">"(?i)Santa|Christmas"</span>),</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Christmas Ducks"</span>, <span class="st">"Other Ducks"</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(asin, title, isChristmasDuck)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our data set of 247 contains nine Christmas-themed rubber ducks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>df_products_isChristmasDuck <span class="sc">|&gt;</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(isChristmasDuck)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; # A tibble: 2 x 2</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   isChristmasDuck     n</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;           &lt;int&gt;</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1 Christmas Ducks     9</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2 Other Ducks       238</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that we have identified whether each duck is Christmas-themed or not, we can visualize our historical product data set conditional on this information.</p>
</section>
<section id="visualize-sales-rank-development" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="visualize-sales-rank-development"><span class="header-section-number">3.2</span> Visualize Sales Rank Development</h2>
<p>For this analysis, we aim to visualize the sales rank development over time as a proxy for the products’ sales. Since we are interested in how well Christmas-themed rubber ducks sell compared to non-Christmas (i.e., “other”) rubber ducks, we visualize the mean daily sales rank for each of those two groups. Also, we generate a new variable <code>isChristmasSeason</code>, which indicates whether the observation is shortly before Christmas (i.e., between <code>2023-11-01</code> and <code>2023-12-25</code>) or outside the Christmas season. The following code prepares the data accordingly and ensures that we include only the year <code>2023</code> for illustrative purposes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df_panel_season_2023 <span class="ot">&lt;-</span> df_panel_joined <span class="sc">|&gt;</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_products_isChristmasDuck, <span class="at">by =</span> <span class="st">"asin"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasSeason =</span> <span class="fu">if_else</span>(</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>      date <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023-11-01"</span>) <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-25"</span>),</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>, <span class="cn">FALSE</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date, isChristmasDuck, isChristmasSeason) <span class="sc">|&gt;</span> </span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">salesRank =</span> <span class="fu">mean</span>(salesRank, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date <span class="sc">&gt;=</span> <span class="st">"2023-01-01"</span> <span class="sc">&amp;</span> date <span class="sc">&lt;=</span> <span class="st">"2023-12-31"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasSeason =</span> <span class="fu">if_else</span>(</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>      isChristmasSeason, <span class="st">"Christmas Season"</span>,</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Before Christmas Season"</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasSeason =</span> <span class="fu">relevel</span>(</span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.factor</span>(isChristmasSeason), <span class="at">ref =</span> <span class="st">"Before Christmas Season"</span></span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasDuck =</span> <span class="fu">as.factor</span>(isChristmasDuck),</span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasDuck =</span> <span class="fu">relevel</span>(</span>
<span id="cb45-25"><a href="#cb45-25" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as.factor</span>(isChristmasDuck), <span class="at">ref =</span> <span class="st">"Other Ducks"</span></span>
<span id="cb45-26"><a href="#cb45-26" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb45-27"><a href="#cb45-27" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For the interpretation of the following analysis, remember that a <em>higher</em> sales rank means <em>fewer</em> sales. The best-selling product exhibits a sales rank of one within its category. The lower the sales of the product, the higher its sales rank. Thus, the sales rank decreases when the product sells better.</p>
<p><a href="#fig-sales-rank-time-series" class="quarto-xref">Figure&nbsp;3</a> plots the mean sales rank over time for <em>Christmas-themed</em> and <em>other</em> rubber ducks. The shaded area indicates the Christmas season in November and December, leading to Christmas Day on December 25. Based on <a href="#fig-sales-rank-time-series" class="quarto-xref">Figure&nbsp;3</a>, sales of Christmas rubber ducks appear to be strongly seasonal. During the weeks before Christmas, the sales rank decreases substantially, which implies higher sales (note that the y-axis is inverted, such that a lower sales rank—reflecting more sales—appears higher).</p>
<p>In comparison, the sales rank of the <em>other ducks</em> decreases less strongly. Thus, both product groups seem to sell better during the Christmas period—compared to all other products in the same root category. But this increase in sales appears much stronger for Christmas-themed rubber ducks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>df_panel_season_2023 <span class="sc">|&gt;</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    date, salesRank,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> isChristmasDuck, <span class="at">label =</span> isChristmasDuck)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">xintercept =</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-25"</span>),</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom =</span> <span class="st">"rect"</span>,</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">xmin =</span> <span class="fu">as.Date</span>(<span class="st">"2023-11-01"</span>),</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">xmax =</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-25"</span>),</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">ymin =</span> <span class="sc">-</span><span class="cn">Inf</span>,</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">ymax =</span> <span class="sc">+</span><span class="cn">Inf</span>,</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reverse</span>(<span class="at">label =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkgrey"</span>, <span class="st">"darkred"</span>)) <span class="sc">+</span></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Sales Rank"</span></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>isChristmasDuck, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-sales-rank-time-series" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-sales-rank-time-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Sales Rank Development of Christmas-Themed vs.&nbsp;Other Rubber Ducks Before and During Christmas Season
</figcaption>
<div aria-describedby="fig-sales-rank-time-series-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="keepar_files/figure-html/fig-sales-rank-time-series-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="difference-in-differences-estimation" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="difference-in-differences-estimation"><span class="header-section-number">3.3</span> Difference-in-Differences Estimation</h2>
<p>We now want to quantify the difference-in-differences between the sales rank of Christmas-themed vs.&nbsp;other rubber ducks before and during the Christmas period. Thus, we designate the Christmas-themed rubber ducks as the treatment and the other rubber ducks as the control group.</p>
<p>Before we estimate the corresponding regression model, we visualize the difference-in-differences between the treatment and control group before and during the Christmas season.</p>
<p>By comparing the respective mean sales ranks, <a href="#fig-sales-rank-did" class="quarto-xref">Figure&nbsp;4</a> shows that the sales rank of Christmas-themed rubber ducks decreases much more strongly (note the reversed y-axis) than the control group of other rubber ducks. Again, this visualization implies that Christmas-themed rubber ducks sell particularly well, even beyond the expected increase in sales for all rubber ducks during the Christmas season.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>df_panel_season_2023 <span class="sc">|&gt;</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(isChristmasDuck, isChristmasSeason) <span class="sc">|&gt;</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">salesRank =</span> <span class="fu">mean</span>(salesRank), <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> isChristmasSeason, <span class="at">y =</span> salesRank, <span class="at">color =</span> isChristmasDuck, <span class="at">shape =</span> isChristmasDuck)) <span class="sc">+</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> isChristmasDuck), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"darkgrey"</span>, <span class="st">"darkred"</span>)) <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limit =</span> <span class="fu">c</span>(<span class="st">"Before Christmas Season"</span>, <span class="st">"Christmas Season"</span>)) <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_reverse</span>(<span class="at">label =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.minor.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_blank</span>()</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-sales-rank-did" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-sales-rank-did-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Mean Sales Rank for Christmas-Themed vs.&nbsp;Other Rubber Ducks Before and During Christmas Season
</figcaption>
<div aria-describedby="fig-sales-rank-did-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="keepar_files/figure-html/fig-sales-rank-did-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>We then estimate the difference-in-differences model with <code>log(salesRank)</code> as the dependent variable, and <code>isChristmasDuck</code>, <code>isChristmasSeason</code>, as well as their interaction, as independent variables. We take the natural logarithm of each sales rank because it enables a relative interpretation of changes in the sales rank such that we can report more intuitive percentage changes.</p>
<p>More precisely, we aim to estimate the following regression model:</p>
<span class="math display">\[\begin{align}
  log(\mathit{salesRank}_{it}) = \, &amp;\beta_0 + \beta_1 \, \mathit{isChristmasDuck}_i + \, \\
  &amp; \beta_2 \, \mathit{isChristmasSeason}_t \, + \\
  &amp; \gamma \, \mathit{(isChristmasDuck}_i \times \mathit{isChristmasSeason}) + \epsilon_{it}
\end{align}\]</span>
<p>We can then interpret the estimated coefficient <span class="math inline">\(\hat\gamma\)</span> of the interaction term of <code>isChristmasDuck</code> and <code>isChristmasSeason</code> as the incremental relative difference in <code>salesRanks</code> of Christmas vs. non-Christmas rubber ducks during the Christmas season.</p>
<p>We can estimate and visualize this regression analysis with the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>reg_1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">log</span>(salesRank) <span class="sc">~</span> isChristmasDuck <span class="sc">*</span> isChristmasSeason,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_panel_season_2023</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-tbl-cap="Difference-in-Differences Estimates for the Impact of the Christmas Season on the Sales Ranks of Christmas-Themed Rubber Ducks">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  reg_1, <span class="at">markdown =</span> <span class="cn">TRUE</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dict =</span> <span class="fu">c</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasDuckChristmasDucks =</span> <span class="st">"Christmas Duck"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">isChristmasSeasonChristmasSeason =</span> <span class="st">"Christmas Season"</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tbl-regression-did" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-did-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Difference-in-Differences Estimates for the Impact of the Christmas Season on the Sales Ranks of Christmas-themed Rubber Ducks
</figcaption>
<div aria-describedby="tbl-regression-did-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/etable/etable_tex_2024-05-13_1123236403.png" class="img-fluid figure-img" style="width:80.0%">
</div>
</figure>
</div>
<p><a href="#tbl-regression-did" class="quarto-xref">Table&nbsp;2</a> displays the estimation results for the impact of the Christmas season on the sales rank of Christmas-themed rubber ducks in comparison to other rubber ducks.</p>
<p>Interpreting the coefficient of the <code>Christmas Duck x Christmas Season</code> interaction (= -0.1260874), we see that Christmas-themed rubber ducks exhibit a lower sales rank by -11.85% (<span class="math inline">\(=(exp(\hat{\beta})-1)\times 100\%\)</span>) compared to non-Christmas-themed rubber ducks during the Christmas season. This result confirms our intuition and the visual analysis of the data.</p>
<p>While this analysis is relatively simple, it illustrates how researchers can use the acquired and transformed data to estimate standard econometric models.</p>
</section>
</section>
<section id="summary-conclusions-and-outlook" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Summary, Conclusions, and Outlook</h1>
<p>This article has introduced the <code>keepar</code> package. Using this package, I demonstrated how to</p>
<ol type="1">
<li><p>identify products from Keepa’s Amazon product database,</p></li>
<li><p>obtain (historical) product data, and</p></li>
<li><p>transform this raw data into a tidy panel data set.</p></li>
</ol>
<p>Illustrated with the example of rubber ducks on Amazon, this procedure generated a suitable data set for a difference-in-differences analysis. This article showcased such analysis by estimating the impact of the Christmas season on the sales ranks of Christmas-themed rubber ducks as compared to other rubber ducks.</p>
<p>Researchers can use the <code>keepar</code> package and its functions to simplify working with Keepa’s Amazon product data in <code>R</code>. Thus, researchers can focus on tasks related to answering substantive research questions instead of spending time acquiring and transforming the data.</p>
<p>This paper has introduced the core functionality of the <code>keepar</code> package, focused on obtaining select product-related metadata and historical information concerning prices, sales ranks, star ratings, and number of reviews. Beyond this capability, the package can also extract historical information concerning competing offers for the same product (i.e., multiple offers from different sellers for the same product). Furthermore, <code>keepar</code> users can extract information on sellers, such as the seller rating. Readers can find all available functions in the package documentation (accessible through <code>help(package = keepar)</code>), which explains in detail how to use the functions.</p>
<p>However, the package does not cover all available methods from the Keepa API. Further versions of <code>keepar</code> could integrate the product search method, which mirrors a search request through Amazon’s search engine, or the best seller request, which returns the best-selling list for a specified category. I encourage other researchers to collaborate and contribute to the package via its <a href="https://github.com/lukas-jue/keepar">GitHub repository</a> <span class="citation" data-cites="jürgensmeier2024e">(<a href="#ref-jürgensmeier2024e" role="doc-biblioref">Jürgensmeier 2024</a>)</span>.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-angrist2009a" class="csl-entry" role="listitem">
Angrist, Joshua D., and Jörn-Steffen Pischke. 2009. <em>Mostly Harmless Econometrics: An Empiricist’s Companion</em>. Princeton University Press.
</div>
<div id="ref-boegershausen2022" class="csl-entry" role="listitem">
Boegershausen, Johannes, Hannes Datta, Abhishek Borah, and Andrew T. Stephen. 2022. <span>“Fields of Gold: Scraping Web Data for Marketing Insights.”</span> <em>Journal of Marketing</em> 86 (5): 1–20. <a href="https://doi.org/10.1177/00222429221100750">https://doi.org/10.1177/00222429221100750</a>.
</div>
<div id="ref-bryan2017" class="csl-entry" role="listitem">
Bryan, Jenny. 2017. <span>“Project-Oriented Workflow.”</span> <a href="https://www.tidyverse.org/blog/2017/12/workflow-vs-script/">https://www.tidyverse.org/blog/2017/12/workflow-vs-script/</a>.
</div>
<div id="ref-card1993" class="csl-entry" role="listitem">
Card, David, and Alan Krueger. 1993. <span>“Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania.”</span> <em>American Economic Review</em> 84 (4): 772–93. <a href="https://doi.org/10.3386/w4509">https://doi.org/10.3386/w4509</a>.
</div>
<div id="ref-farronato2023" class="csl-entry" role="listitem">
Farronato, Chiara, Andrey Fradkin, and Alexander MacKay. 2023. <span>“Self-Preferencing at Amazon: Evidence from Search Rankings.”</span> <em>AEA Papers and Proceedings</em> 113 (May): 239–43. <a href="https://doi.org/10.1257/pandp.20231068">https://doi.org/10.1257/pandp.20231068</a>.
</div>
<div id="ref-giorgi2022" class="csl-entry" role="listitem">
Giorgi, Federico M., Carmine Ceraolo, and Daniele Mercatelli. 2022. <span>“The R Language: An Engine for Bioinformatics and Data Science.”</span> <em>Life</em> 12 (5): 648. <a href="https://doi.org/10.3390/life12050648">https://doi.org/10.3390/life12050648</a>.
</div>
<div id="ref-ihaka1996" class="csl-entry" role="listitem">
Ihaka, Ross, and Robert Gentleman. 1996. <span>“R: A Language for Data Analysis and Graphics.”</span> <em>Journal of Computational and Graphical Statistics</em> 5 (3): 299314. <a href="https://doi.org/10.1080/10618600.1996.10474713">https://doi.org/10.1080/10618600.1996.10474713</a>.
</div>
<div id="ref-jürgensmeier2024e" class="csl-entry" role="listitem">
Jürgensmeier, Lukas. 2024. <span>“GitHub Repository for the ‘<span>k</span>eepar‘ R Package.”</span> <a href="https://github.com/lukas-jue/keepar">https://github.com/lukas-jue/keepar</a>.
</div>
<div id="ref-jürgensmeier2024d" class="csl-entry" role="listitem">
Jürgensmeier, Lukas, Jan Bischoff, and Bernd Skiera. 2024. <span>“Opportunities for Self-Preferencing on International Online Retail Platforms.”</span> <em>International Marketing Review</em> conditionally accepted.
</div>
<div id="ref-jürgensmeier2024b" class="csl-entry" role="listitem">
Jürgensmeier, Lukas, and Bernd Skiera. 2024. <span>“Measuring Self-Preferencing on Digital Platforms.”</span> <em>Working Paper</em>. <a href="https://papers.ssrn.com/abstract=4393726">https://papers.ssrn.com/abstract=4393726</a>.
</div>
<div id="ref-kaszynski2024" class="csl-entry" role="listitem">
Kaszynski, Alex. 2024. <em>Keepa Python Library</em>. <a href="https://github.com/akaszynski/keepa">https://github.com/akaszynski/keepa</a>.
</div>
<div id="ref-keepa2024a" class="csl-entry" role="listitem">
Keepa. 2024a. <em>Keepa.com API Java Framework</em>. <a href="https://github.com/keepacom/api_backend">https://github.com/keepacom/api_backend</a>.
</div>
<div id="ref-keepa2024b" class="csl-entry" role="listitem">
———. 2024b. <em>Keepa.com API PHP Framework</em>. <a href="https://github.com/keepacom/php_api">https://github.com/keepacom/php_api</a>.
</div>
<div id="ref-keepa2024c" class="csl-entry" role="listitem">
———. 2024c. <span>“Keepa - Amazon Price Tracker.”</span> <a href="https://keepa.com/#!">https://keepa.com/#!</a>
</div>
<div id="ref-lanxner2019" class="csl-entry" role="listitem">
Lanxner, Eyal. 2019. <span>“How to Master and Win the Amazon Buy Box.”</span> <a href="https://www.bigcommerce.co.uk/blog/win-amazon-buy-box/">https://www.bigcommerce.co.uk/blog/win-amazon-buy-box/</a>.
</div>
<div id="ref-reimers2023" class="csl-entry" role="listitem">
Reimers, Imke, and Joel Waldfogel. 2023. <span>“A Framework for Detection, Measurement, and Welfare Analysis of Platform Bias.”</span> <em>Working Paper</em>, NBER Working Paper 31766, October. <a href="https://doi.org/10.3386/w31766">https://doi.org/10.3386/w31766</a>.
</div>
<div id="ref-waldfogel2024" class="csl-entry" role="listitem">
Waldfogel, Joel. 2024. <span>“Amazon Self-Preferencing in the Shadow of the Digital Markets Act.”</span> <em>Working Paper</em>, Working paper series, April. <a href="https://doi.org/10.3386/w32299">https://doi.org/10.3386/w32299</a>.
</div>
<div id="ref-wickham2019" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the Tidyverse.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-zeibak2020" class="csl-entry" role="listitem">
Zeibak, Leanna. 2020. <span>“How to Win the Amazon Buy Box in 2021.”</span> <a href="https://tinuiti.com/blog/amazon/win-amazon-buy-box/">https://tinuiti.com/blog/amazon/win-amazon-buy-box/</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/lukas-juergensmeier\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>